### ISSUE TITLE
Reimplement the operation history widget

### ISSUE THREAD

**Issue by cloderic** [craft-ai/react-craft-ai-components#15]
# Objectives #

- Get rid of react-infinite
- Latest to earliest scrolling

**Comment by Giska** [comment]
Widget integrated.

Left issues:
- https://github.com/craft-ai/craft-ai/issues/1802
- https://github.com/craft-ai/craft-ai/issues/1840

**Comment by rmdh** [comment]
@Giska with the remaining issues in store, can we close this?

**Comment by rmdh** [comment]
Giska: The remaining issues referenced above are not solved yet

**Comment by PierreSalaun** [comment]
Another related issue: https://github.com/craft-ai/craft-ai/issues/2509

**Comment by PierreSalaun** [comment]
Closing this particular issue, other bugs will being referenced in dedicated issues.
