### ISSUE TITLE
Huge trees are difficult to visualize

### ISSUE THREAD

**Issue by Totoketchup** [craft-ai/react-craft-ai-components#17]
Loading a very large and deep tree makes the visualization very difficult.
The idea would be to limit the size of the visualized tree in terms of width and depth.

Example with the following tree:
[chess.txt](https://github.com/craft-ai/react-craft-ai-components/files/2566521/chess.txt)

**Comment by cloderic** [comment]
Folding ?
To be prototyped.

**Comment by Totoketchup** [comment]
solved by https://github.com/craft-ai/react-craft-ai-components/pull/30
